### ISSUE TITLE
Boundaries Map - Zoom with Scroll Wheel Integration

### ISSUE THREAD

**Issue by office-cb5** [BetaNYC/Boundaries-Map#30]
Hi BetaNYC!  

I love your Boundaries Map!   Would it be possible to integrate the input from a scroll wheel on a mouse in order to zoom into the map?  

All the best and thanks!

Luke @ CB5 Manhattan :)

**Comment by zhik** [comment]
Hey, @office-cb5 Luke, we added scroll wheel zoom and ZIP Codes in the latest update. #29 
Please let us know if you would like any other improvements. 
Thanks!

**Comment by office-cb5** [comment]
You guys are the best!  Thanks so much!

*Luke Szabados* | Community Associate | *Community Board Five*
450 Seventh Avenue, #2109 | New York, NY 10123
T: 212-465-0907 | F: 212-465-1628 | luke@cb5.org
