### ISSUE TITLE
Carto API key is exposed

### ISSUE THREAD

**Issue by jtanadi** [BetaNYC/Boundaries-Map#39]
Related to issue #11 

Currently, data is fetched directly from Carto on the front end, so even though the key itself is stored in an `.env` and concatenated with the url, it is still being exposed when the browser fetches data (especially since the api key is part of a query string).

Line below is one of a small handful of lines referencing `api_key`:
https://github.com/BetaNYC/Boundaries-Map/blob/7fd7a6f2072514eb7be28c07d685525c5cb90a1a/src/js/index.js#L333

API key is visible in network requests and query string:
![Screen Shot 2020-02-03 at 5 18 37 PM](https://user-images.githubusercontent.com/18740288/73696488-61f43380-46aa-11ea-833a-ab9363ee7c91.png)
![Screen Shot 2020-02-03 at 5 27 45 PM](https://user-images.githubusercontent.com/18740288/73696637-ae3f7380-46aa-11ea-94c8-79d43f6e6713.png)

It's best to move resource fetching with keys and secrets to the back end. The front end can then fetch data from the back end without exposing the api key.

**Comment by zhik** [comment]
@jtanadi thanks for noticing the issue. I am not sure if we are going to create a backend, as we still intend to use gh pages for hosting.

Anyways the API key exposed on the gh-pages/production is a public key with only SELECT functions enabled.

**Comment by jtanadi** [comment]
It's possible to have the app hosted on gh pages and have a separate back end just for making these kinds of API calls without hosting anything. That internal API endpoint could also be something that all BetaNYC apps share (eg. if there's an `api.betanyc.com` subdomain that all apps fetch data from). Another option is to use something like AWS Lambda.

But anyway, fair enough—this can easily complicate something that's supposed to be simple. Seems like if an api key's functionality is restricted, it should be ok (although I'm not a security expert, so don't quote me on that).
